-- dt_intervals.sql - Tuesday, November 29, 2022
/*      Playing with Python's timedelta and PostgreSQL's INTERVAL
 */

SET search_path TO media_library,public;

DROP TABLE IF EXISTS dt_intervals;

CREATE TABLE IF NOT EXISTS dt_intervals (
	id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY(START WITH 10001),
	epoch_from	FLOAT NOT NULL,
	epoch_thru	FLOAT NOT NULL,
	played_from     TIMESTAMPTZ NOT NULL,
	played_thru    	TIMESTAMPTZ NOT NULL,
	play_secs       FLOAT,
	play_time	INTERVAL
);
