"""Initial build

Revision ID: 3bfc5d8e82d2
Revises: 
Create Date: 2022-06-17 12:18:28.495436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfc5d8e82d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt_fileinfo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=100001), nullable=False),
    sa.Column('pathname', sa.String(length=1024), nullable=False),
    sa.Column('asof', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pathname'),
    schema='media_library'
    )
    op.create_index('idx_fileinfo_asof_desc', 'dt_fileinfo', [sa.text('asof DESC')], unique=False, schema='media_library')
    op.create_index(op.f('ix_media_library_dt_fileinfo_asof'), 'dt_fileinfo', ['asof'], unique=False, schema='media_library')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_index(op.f('ix_media_library_dt_fileinfo_asof'), table_name='dt_fileinfo', schema='media_library')
    op.drop_index('idx_fileinfo_asof_desc', table_name='dt_fileinfo', schema='media_library')
    op.drop_table('dt_fileinfo', schema='media_library')
    # ### end Alembic commands ###
