"""Initial build

Revision ID: d807675dd3cb
Revises: 
Create Date: 2022-11-28 11:49:19.013107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd807675dd3cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt_playhistory',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=100001), nullable=False),
    sa.Column('epochtime', sa.Float(), nullable=False),
    sa.Column('playdate', sa.Date(), nullable=False),
    sa.Column('playdatetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('play_secs', sa.Float(), nullable=True),
    sa.Column('play_time', sa.Interval(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('epochtime'),
    schema='media_library'
    )
    op.create_index(op.f('ix_media_library_dt_playhistory_epochtime'), 'dt_playhistory', ['epochtime'], unique=True, schema='media_library')
    op.create_index(op.f('ix_media_library_dt_playhistory_filename'), 'dt_playhistory', ['filename'], unique=False, schema='media_library')
    op.create_index(op.f('ix_media_library_dt_playhistory_playdate'), 'dt_playhistory', ['playdate'], unique=False, schema='media_library')
    op.create_index(op.f('ix_media_library_dt_playhistory_playdatetime'), 'dt_playhistory', ['playdatetime'], unique=False, schema='media_library')

    op.create_table('dt_playinfo',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=100001), nullable=False),
    sa.Column('epochtime', sa.Float(), nullable=False),
    sa.Column('playdate', sa.Date(), nullable=False),
    sa.Column('playdatetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('epochtime'),
    schema='media_library'
    )
    op.create_index(op.f('ix_media_library_dt_playinfo_epochtime'), 'dt_playinfo', ['epochtime'], unique=True, schema='media_library')
    op.create_index(op.f('ix_media_library_dt_playinfo_filename'), 'dt_playinfo', ['filename'], unique=False, schema='media_library')
    op.create_index(op.f('ix_media_library_dt_playinfo_playdate'), 'dt_playinfo', ['playdate'], unique=False, schema='media_library')
    op.create_index(op.f('ix_media_library_dt_playinfo_playdatetime'), 'dt_playinfo', ['playdatetime'], unique=False, schema='media_library')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_library_dt_playinfo_playdatetime'), table_name='dt_playinfo', schema='media_library')
    op.drop_index(op.f('ix_media_library_dt_playinfo_playdate'), table_name='dt_playinfo', schema='media_library')
    op.drop_index(op.f('ix_media_library_dt_playinfo_filename'), table_name='dt_playinfo', schema='media_library')
    op.drop_index(op.f('ix_media_library_dt_playinfo_epochtime'), table_name='dt_playinfo', schema='media_library')
    op.drop_table('dt_playinfo', schema='media_library')
    op.drop_index(op.f('ix_media_library_dt_playhistory_playdatetime'), table_name='dt_playhistory', schema='media_library')
    op.drop_index(op.f('ix_media_library_dt_playhistory_playdate'), table_name='dt_playhistory', schema='media_library')
    op.drop_index(op.f('ix_media_library_dt_playhistory_filename'), table_name='dt_playhistory', schema='media_library')
    op.drop_index(op.f('ix_media_library_dt_playhistory_epochtime'), table_name='dt_playhistory', schema='media_library')
    op.drop_table('dt_playhistory', schema='media_library')
    # ### end Alembic commands ###
